In [1]:
import numpy as np

## 행렬의 연산

In [13]:
x = np.array([[1,2],
              [3,4]])     # 2x2

y = np.array([[1, 2, 3],
              [4, 5, 6]]) # 2x3

print(np.dot(x,y))        # 2x3

[[ 9 12 15]
 [19 26 33]]


## Transposition

In [14]:
# (AT)T = A
# (AB)  = BTAT

In [17]:
y = np.array([[1, 2, 3],
              [4, 5, 6]])

y

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
y.T

array([[1, 4],
       [2, 5],
       [3, 6]])

## 인공신공망 간단 구현

In [28]:
def sigmoid(x) :
    return 1 / (1 + np.exp(-x))

def identity_function(x) :
    return x

def softmax(x) :
    if x.ndim == 2 :
        x = x.T
        x = x - np.max(x, axis = 0)
        y = np.exp(x) / np.sum(np.exp(x), axis = 0)
        
        return y.T
    
    x = x - np.max(x) #오버플로 대책
    return np.exp(x) / np.sum(np.exp(x))

In [29]:
def init_network():
    network = {}
    
    #-----------------------------------------
    network['W1'] = np.array([[0.1, 0.3, 0.5], 
                              [0.2, 0.4, 0.6]])
    
    network['B1'] = np.array([0.1, 0.2, 0.3])
    
    #-----------------------------------------
    
    network['W2'] = np.array([[0.1, 0.4], 
                              [0.2, 0.5], 
                              [0.3, 0.6]])
    
    network['B2'] = np.array([0.1, 0.2])
    
    #-----------------------------------------
    
    network['W3'] = np.array([[0.1, 0.3], 
                              [0.2, 0.4]])
    
    network['B3'] = np.array([0.1, 0.2])
    
    #-----------------------------------------
    
    return network

def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['B1'], network['B2'], network['B3']

    # 1*2 2*3 = 1*3
    a1 = np.dot(x, W1) + b1
    z1 = sigmoid(a1)
    
    # 1*3 3*2 = 1*2
    a2 = np.dot(z1, W2) + b2
    z2 = sigmoid(a2)
    
    # 1*2 2*2 = 1*2
    a3 = np.dot(z2, W3) + b3
    y = softmax(a3)

    return y

In [30]:
network = init_network()

x = np.array([1.0, 0.5])
y = forward(network, x)

print(y)    # [0.31682708 0.69627909]

[0.40625907 0.59374093]
