In [16]:
import numpy as np
import pandas as pd
import csv
import time

np.random.seed(1234)
def randomize(): np.random.seed(time.time())

In [17]:
RND_MEAN = 0
RND_STD = 0.0030

LEARNING_RATE = 0.001

## load_abalone_dataset

In [35]:
with open('abalone.csv') as csvfile:
    csvreader = csv.reader(csvfile)
    next(csvreader, None)
    rows = []
    for row in csvreader:
        rows.append(row)

print(pd.DataFrame(rows))

global data, input_cnt, output_cnt
input_cnt, output_cnt = 10, 1
data = np.zeros([len(rows), input_cnt + output_cnt])

print(data)

for n, row in enumerate(rows):
    if row[0] == 'I': data[n, 0] = 1
    if row[0] == 'M': data[n, 1] = 1
    if row[0] == 'F': data[n, 2] = 1
    data[n, 3:] = row[1:]
print()
print(data)
print()

#    data[n, 3:] = row[1:]
pd.DataFrame(data)

      0      1      2      3       4       5       6       7   8
0     M  0.455  0.365  0.095   0.514  0.2245   0.101    0.15  15
1     M   0.35  0.265   0.09  0.2255  0.0995  0.0485    0.07   7
2     F   0.53   0.42  0.135   0.677  0.2565  0.1415    0.21   9
3     M   0.44  0.365  0.125   0.516  0.2155   0.114   0.155  10
4     I   0.33  0.255   0.08   0.205  0.0895  0.0395   0.055   7
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4172  F  0.565   0.45  0.165   0.887    0.37   0.239   0.249  11
4173  M   0.59   0.44  0.135   0.966   0.439  0.2145  0.2605  10
4174  M    0.6  0.475  0.205   1.176  0.5255  0.2875   0.308   9
4175  F  0.625  0.485   0.15  1.0945   0.531   0.261   0.296  10
4176  M   0.71  0.555  0.195  1.9485  0.9455  0.3765   0.495  12

[4177 rows x 9 columns]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

[[ 0.      1.      0.     ...  0.101  

0    1    2      3      4      5       6       7       8       9     10
0     0.0  1.0  0.0  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.1500  15.0
1     0.0  1.0  0.0  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7.0
2     0.0  0.0  1.0  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9.0
3     0.0  1.0  0.0  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10.0
4     1.0  0.0  0.0  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7.0
...   ...  ...  ...    ...    ...    ...     ...     ...     ...     ...   ...
4172  0.0  0.0  1.0  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11.0
4173  0.0  1.0  0.0  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10.0
4174  0.0  1.0  0.0  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9.0
4175  0.0  0.0  1.0  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10.0
4176  0.0  1.0  0.0  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12.0

[4177 rows x 11 columns]

## train_and_test

In [40]:
global weight, bias, input_cnt, output_cnt

In [43]:
weight = np.random.normal(RND_MEAN, RND_STD,[input_cnt, output_cnt])

In [49]:
weight

array([[ 1.41430549e-03],
       [-3.57292708e-03],
       [ 4.29812091e-03],
       [-9.37955688e-04],
       [-2.16176620e-03],
       [ 2.66148882e-03],
       [ 2.57876524e-03],
       [-1.90957051e-03],
       [ 4.70891163e-05],
       [-6.72805486e-03]])

In [50]:
bias = np.zeros([output_cnt])

In [52]:
bias

array([0.])

## train_and_test

In [100]:
mb_size = 10

global data, shuffle_map, test_begin_idx
shuffle_map = np.arange(data.shape[0])
np.random.shuffle(shuffle_map)
step_count = int(data.shape[0] * 0.8) // mb_size
test_begin_idx = step_count * mb_size

In [101]:
shuffle_map

array([2621, 2731, 1989, ...,  661, 2459,  773])

In [102]:
int(data.shape[0] * 0.8)

3341

In [103]:
int(data.shape[0] * 0.8) // mb_size

334

In [105]:
test_begin_idx

3340

In [120]:
data[shuffle_map[test_begin_idx:]]

array([[ 1.    ,  0.    ,  0.    , ...,  0.1055,  0.1295,  6.    ],
       [ 1.    ,  0.    ,  0.    , ...,  0.2035,  0.253 ,  9.    ],
       [ 0.    ,  1.    ,  0.    , ...,  0.1455,  0.28  , 13.    ],
       ...,
       [ 1.    ,  0.    ,  0.    , ...,  0.1555,  0.295 , 11.    ],
       [ 0.    ,  0.    ,  1.    , ...,  0.2325,  0.358 , 20.    ],
       [ 0.    ,  1.    ,  0.    , ...,  0.158 ,  0.12  ,  9.    ]])

In [118]:
global data, shuffle_map, test_begin_idx, output_cnt
test_data = data[shuffle_map[test_begin_idx:]]
test_data[:, :-output_cnt], test_data[:, -output_cnt:]

(array([[1.    , 0.    , 0.    , ..., 0.2355, 0.1055, 0.1295],
        [1.    , 0.    , 0.    , ..., 0.445 , 0.2035, 0.253 ],
        [0.    , 1.    , 0.    , ..., 0.316 , 0.1455, 0.28  ],
        ...,
        [1.    , 0.    , 0.    , ..., 0.3055, 0.1555, 0.295 ],
        [0.    , 0.    , 1.    , ..., 0.3975, 0.2325, 0.358 ],
        [0.    , 1.    , 0.    , ..., 0.1675, 0.158 , 0.12  ]]),
 array([[ 6.],
        [ 9.],
        [13.],
        [ 9.],
        [ 8.],
        [ 7.],
        [10.],
        [ 7.],
        [10.],
        [ 9.],
        [11.],
        [ 4.],
        [ 8.],
        [15.],
        [10.],
        [18.],
        [10.],
        [11.],
        [11.],
        [10.],
        [19.],
        [ 5.],
        [ 9.],
        [ 9.],
        [10.],
        [10.],
        [10.],
        [ 7.],
        [ 7.],
        [11.],
        [ 8.],
        [10.],
        [ 9.],
        [ 5.],
        [10.],
        [13.],
        [ 8.],
        [ 8.],
        [19.],
        [ 6.],
       

In [119]:
test_data.shape

(837, 11)

In [123]:
test_data[:, :-output_cnt]

array([[1.    , 0.    , 0.    , ..., 0.2355, 0.1055, 0.1295],
       [1.    , 0.    , 0.    , ..., 0.445 , 0.2035, 0.253 ],
       [0.    , 1.    , 0.    , ..., 0.316 , 0.1455, 0.28  ],
       ...,
       [1.    , 0.    , 0.    , ..., 0.3055, 0.1555, 0.295 ],
       [0.    , 0.    , 1.    , ..., 0.3975, 0.2325, 0.358 ],
       [0.    , 1.    , 0.    , ..., 0.1675, 0.158 , 0.12  ]])