In [19]:
import numpy as np
import tensorflow as tf

In [ ]:
### random_uniform

- tf.square(a)   # 제곱
- tf.sqrt(a)     # 제곱근
- tf.matmul(a,b) # 두 텐서의 점곱을 계산

In [1]:
# CNN than
# RNN 자연어처리

### GradientTape()  API
- https://blog.csdn.net/TFATS/article/details/110636225

In [22]:
input_var = tf.Variable(initial_value=3.)

with tf.GradientTape() as tape :
    result = tf.square(input_var)
    
gradient = tape.gradient(result, input_var)

- gradient = tape.gradient(loss, weights)와 같이 가중치에 대한 모델 손실의 그레이디언트를 계산하는 데 가장 널리 사용되는 방법이다.
- 실제로 입력은 어떤 텐서라도 가능하지만 텐서플로는 기존벅으로 푼련 가능한 변수만 추적함
- 따라서 상수 텐서의 경우 tape.watch()를 호출하여 추적한다는 것을 **수동으로 알려주야함**


- **이유 : 비용이 많이 들어**
- **자원낭비를 막기위해 훈련 가능한 변수는 기본적으로 감시 대상이고, 훈련 가능한 변수에 대한 손실의 그레이디언트를 계산하는 것이 그레이디언트 테이프의 주 사용용도다.**

In [24]:
input_const = tf.constant(3.) # 必须是小数点

with tf.GradientTape() as tape :
    tape.watch(input_const)
    result = tf.square(input_const)
    
gradient = tape.gradient(result, input_const)

In [ ]:
time = tf.Varable(0.)

with tf.GradientTape() as outer_tape :
    with tf.GradientTape() as inner_tape :
        position = 4.9 * time ** 2
    

### random.random()

In [15]:
x = np.random.random([32,2])
y = np.random.random([2,32])
print(np.dot(x, y))

[[0.5395578  0.30043796 0.63537347 ... 0.76817709 0.39414578 0.46322635]
 [0.53913278 0.76946294 0.96701229 ... 1.15659937 0.81228188 0.66316484]
 [0.46192238 0.93720315 1.02524551 ... 1.22137537 0.94379289 0.68682826]
 ...
 [0.77750611 0.85493198 1.21426435 ... 1.45679366 0.94426841 0.84764146]
 [0.57154642 0.41428085 0.74101253 ... 0.89333136 0.50314538 0.53168012]
 [0.17799942 0.50266394 0.49523797 ... 0.58797162 0.48987871 0.32507221]]


### np.tanspose() = T

In [38]:
# np.tanspose(x)
# T와 같다

x = np.zeros([5, 1])
x = x.T
x = x.T

x = x.transpose()
x = x.transpose()
x

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

### 2D 회전

In [39]:
# 2D 회전 :: 
# R = [[cos(theta), -sin(theta)] , [sin(theta), cos(theta)]] 와 점곱하여 얻음

In [40]:
# 점곱으로 2D 크기 변경
# S = [[horizontal_factor, 0], [0, vertical_factor]]

### tf.random.normal()

In [12]:
x = tf.random.normal(shape=(3,1), mean=0, stddev = 1)
x

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[-0.35965142],
       [-0.56284493],
       [ 0.24498485]], dtype=float32)>

### tf.Variable()

In [13]:
v = tf.Variable(initial_value = tf.random.normal(shape=(3,1)))
v

<tf.Variable 'Variable:0' shape=(3, 1) dtype=float32, numpy=
array([[ 1.0724965 ],
       [-1.9688529 ],
       [-0.17836842]], dtype=float32)>

### tf.assign()
- https://blog.csdn.net/Invokar/article/details/89041501

In [14]:
v.assign(tf.ones([3,1]))

<tf.Variable 'UnreadVariable' shape=(3, 1) dtype=float32, numpy=
array([[1.],
       [1.],
       [1.]], dtype=float32)>

In [18]:
ref_a = tf.Variable(tf.constant(1))
ref_b = tf.Variable(tf.constant(2))
update = tf.assign(ref_a, 10)
ref_sum = tf.add(ref_a, ref_b)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(ref_sum))

AttributeError: module 'tensorflow' has no attribute 'assign'